measurement_types = [
    'milliliter',
    'liter',
    'teaspoon',
    'tablespoon',
    'cup',
    'pint',
    'quart',
    'gallon',
    'gram',
    'milligram',
    'kilogram',
    'pound',
    'ounce',
    'pinch',
    'drop',
    'stick',
    'fluid ounce',
    'clove',
    'bulb',
    'head',
    'stalk',
    'small',
    'medium',
    'large',
]

sorted_measurement_types = ['bulb', 'clove', 'cup', 'drop', 'fluid ounce', 'gallon', 'gram', 'head', 'kilogram', 'liter', 'milligram', 'milliliter', 'ounce', 'pinch', 'pint', 'pound', 'quart', 'stalk', 'stick', 'tablespoon', 'teaspoon']
