import random

comments = []

user_ids = list(range(1, 24))
recipe_ids = list(range(1, 25))

for _ in range(88):
    comment = {
        "recipe_id": random.choice(recipe_ids),
        "user_id": random.choice(user_ids),
        "text": random.choice([
            "This recipe is a game-changer! It's so easy to make and tastes like a gourmet dish.",
            "I tried this last night, and it was a disaster. I must have done something wrong. Any tips?",
            "Absolutely love this recipe! It's become a regular in my weekly meal plan.",
            "The combination of ingredients is unique, and the dish turned out amazing!",
            "Not a fan of this one. The flavors didn't quite come together for me.",
            "This recipe is perfect for a quick and satisfying weeknight dinner.",
            "My kids devoured this! It's a family-friendly recipe for sure.",
            "I added a little twist to the recipe by including some extra spices. It was fantastic!",
            "The instructions were easy to follow, and the end result was delicious. A new favorite!",
            "I'm a beginner in the kitchen, and this recipe was simple enough for me. Thanks!",
            "This dish reminds me of my grandma's cooking. It's comfort food at its best.",
            "I can't believe I've been missing out on this recipe. It's now on my regular rotation.",
            "I'm not a fan of cooking, but this recipe was so straightforward. And the taste? Incredible!",
            "My friends were impressed when I served this at our dinner party. Thanks for the recipe!",
            "I'm a vegetarian, and I adapted this recipe by substituting the meat. Still delicious!",
            "I made this for my date night, and it was a hit. I might get a second date because of it!",
            "This recipe is a bit time-consuming, but the end result is totally worth it.",
            "I burned mine. Maybe I'll try again when I'm feeling more confident in the kitchen.",
            "The flavors were too bold for my liking. I'll tone it down next time.",
            "I appreciate the simplicity of the ingredients. It's a budget-friendly recipe!",
            "I'm allergic to one of the main ingredients, so I had to skip this one. Sad face.",
            "This recipe brought back memories of my trip to Italy. So nostalgic and delicious!",
            "I'm on a diet, and this recipe fits perfectly into my meal plan. Healthy and tasty!",
            "I shared this recipe with my colleagues at work, and now we're all cooking it. Yum!",
            "The presentation of this dish is stunning. It's Instagram-worthy for sure.",
            "I made a vegetarian version of this for Meatless Monday. It was a hit!",
            "This recipe saved me when I needed to impress my in-laws. They loved it!",
            "I've never been a fan of cooking, but this recipe made me enjoy the process. Thank you!",
            "I'm not much of a cook, but even I could handle this recipe. And it tasted amazing!",
            "I made this for my anniversary dinner, and it was a romantic success. Thanks!",
            "I've tried many recipes, but this one stands out. It's a keeper!",
            "The aroma while cooking this was heavenly. I felt like a chef in a fancy restaurant.",
            "I'll be honest; I messed up a few steps, but it still turned out great. Forgiving recipe!",
            "My kids are usually picky eaters, but they loved this. It's a miracle recipe!",
            "I'm not usually a fan of spicy food, but I decided to try it. It was surprisingly good!",
            "I made this for a potluck, and everyone asked for the recipe. It's a crowd-pleaser!",
            "I'm a college student on a tight budget, and this recipe is a lifesaver. Tasty and cheap!",
            "I've been craving comfort food, and this hit the spot. So satisfying!",
            "I added a dash of hot sauce for an extra kick. Perfection!",
            "I made this for my parents, and they said it was better than their favorite restaurant.",
            "I'm not the best cook, but this recipe made me feel like a pro. Thank you!",
            "I'm not a fan of the main ingredient, but this recipe changed my mind. Delicious!",
            "I had to substitute a couple of ingredients, but it still turned out delicious.",
            "I'm usually too lazy to cook, but this recipe was surprisingly easy. And tasty!",
            "I made this for my husband's birthday, and he said it was the best meal ever.",
            "I'm a food critic, and I must say, this recipe is top-notch. Well done!",
            "I made this for my book club, and everyone raved about it. A literary masterpiece!",
            "I'm a health nut, and I love how nutritious and delicious this recipe is.",
            "I tried this on a whim, and now it's a regular in my meal rotation. So good!",
            "I've been cooking for years, and this recipe introduced me to new flavors. Impressive!",
            "I made this for my friend who's gluten-free, and she couldn't believe it was GF. Success!",
            "I made this with my kids, and it was a fun and delicious family activity.",
            "I made this for my significant other, and they proposed! Coincidence? I think not!",
            "I'm not a morning person, but this breakfast recipe made me excited to wake up.",
            "I'm usually skeptical of online recipes, but this one exceeded my expectations.",
            "I made this for my daughter's sleepover, and her friends are now requesting the recipe.",
            "I made this for my pet's birthday, and they loved it. Yes, my pet has a birthday!",
            "I made this during a power outage using a camping stove. Resourceful cooking at its best!",
            "I made this with my eyes closed (figuratively), and it still turned out amazing!",
            "I made this for my boss, and now I'm up for a promotion. Thank you, recipe gods!",
            "I made this for my neighbor, and they offered to mow my lawn. Win-win!",
            "I made this for my plant-based friends, and they were shocked at how flavorful it was.",
            "I made this for my gaming marathon, and it fueled me through hours of play. Game on!",
            "I made this for my beach picnic, and it was the highlight of the day. Sandy but satisfied!",
            "I made this for my picky eater, and they asked for seconds. Miracles do happen!",
            "I made this for my friend recovering from surgery, and it brought a smile to their face.",
            "I made this for my potluck, and it disappeared within minutes. A potluck legend!",
            "I made this for my midnight snack, and it made staying up late worth it. Midnight feast!",
            "I made this for my food blog, and it got featured. I'm officially a food influencer now!",
            "I made this for my workout recovery meal, and it replenished my energy. Fit and full!",
            "I made this for my sibling rivalry cook-off, and I emerged victorious. Sibling rivalry conquered!",
            "I made this for my rainy day blues, and it turned my mood around. Rainy days aren't so bad!",
            "I made this for my science experiment-themed dinner, and it was the star of the show.",
            "I made this for my tech-savvy friends, and they declared it the most 'byte'-sized dish ever!",
            "I made this for my holiday dinner, and it brought festive cheer to the table. Ho, ho, ho!",
            "I made this for my monochrome-themed party, and it added a burst of flavor to the black and white.",
            'I made this for my "I don\'t feel like cooking" day, and it required minimal effort. Lazy but tasty!',
            "I made this for my international cuisine night, and it transported everyone's taste buds around the world.",
            "I made this for my hot date, and it was hotter than expected. The dish, not the date!",
            "I made this for my summer barbecue, and it stole the show. Barbecue royalty!",
            "I made this for my self-care day, and it was the ultimate treat. Self-love in every bite!",
            "I made this for my brunch with friends, and it turned a regular morning into a gourmet affair.",
            "I made this for my chemistry-themed dinner, and the reactions at the table were explosive!",
            "I made this for my pet fish, and they swam circles of joy in their bowl. Fish-friendly feast!",
            "I made this for my friend who's never impressed, and they finally admitted it was impressive.",
            "I made this for my potluck at work, and my colleagues are now convinced I'm a secret chef.",
            "I made this for my winter solstice celebration, and it brought warmth to the longest night of the year.",
            "I made this for my surprise dinner party, and it surprised even me with how well it turned out."
        ])
    }
    comments.append(comment)

for _ in range(36):
    comment = {
        "recipe_id": random.choice(recipe_ids),
        "user_id": random.choice(user_ids),
        "text": random.choice([
            "The flavors in this recipe are absolutely delightful. A perfect blend of sweet and savory.",
            "Had a culinary adventure with this recipe! The aroma alone is worth the experience.",
            "Discovered a hidden gem with this dish. It's now a star in my recipe collection.",
            "This recipe is a masterpiece. The presentation and taste are nothing short of extraordinary.",
            "Diving into this culinary delight was like experiencing a symphony of flavors on my taste buds.",
            "Exploring this recipe felt like embarking on a flavor expedition. I'm thoroughly impressed!",
            "The journey through the layers of taste in this dish was a delightful gastronomic experience.",
            "This recipe is a culinary revelation. Each bite tells a story of creativity and deliciousness.",
            "Savoring this dish felt like a stroll through a garden of gastronomic wonders. A true delight!",
            "I couldn't resist the allure of this recipe, and it surpassed all expectations. A culinary triumph!",
            "Embarked on a taste adventure with this recipe, and it was an absolute triumph of flavors!",
            "Delighting my taste buds with this recipe was like discovering a secret world of deliciousness.",
            "This dish is a symphony of flavors, and I felt like a conductor orchestrating a culinary masterpiece.",
            "The culinary magic in this recipe is undeniable. It's not just a dish; it's a work of art!",
            "Tasting this dish was like stepping into a culinary wonderland. The flavors are enchanting!",
            "This recipe is a culinary tapestry, weaving together flavors in a way that captivates the senses.",
            "The artistry in this dish is evident from the first bite. Truly a culinary masterpiece!",
            "Embarking on a flavor journey with this recipe was like discovering a treasure trove of deliciousness.",
            "This dish is a culinary symphony, with each ingredient playing a harmonious tune on the palate.",
            "Indulging in this recipe was like taking a gustatory voyage through a world of exquisite flavors.",
            "The culinary craftsmanship in this dish is impeccable. It's a feast for both the eyes and the taste buds.",
            "Savoring this recipe was like attending a grand banquet of flavors. A truly opulent culinary experience!",
            "This dish is a gastronomic revelation, revealing layers of flavors that dance on the taste buds.",
            "Immersing myself in the flavors of this recipe was like sipping on a cup of culinary bliss.",
            "Delving into the intricate flavors of this dish felt like a journey to the heart of gastronomic excellence.",
            "This recipe is a gastronomic adventure, with each bite revealing a new dimension of flavor.",
            "The culinary symphony of this dish played harmoniously on my palate, creating a delightful sensation.",
            "Tasting this dish was like exploring a flavor labyrinth, with each turn revealing a new and exciting taste.",
            "Embarking on the culinary odyssey of this recipe was a journey of taste bud enlightenment.",
            "This dish is a culinary masterpiece, a canvas of flavors that paints a delicious picture on the palate.",
            "Savoring this recipe was like sipping on the elixir of culinary excellence. Truly extraordinary!",
            "The flavors in this dish are like a symphony, each note harmonizing to create a delightful gastronomic experience.",
            "This recipe is a culinary adventure, with each bite uncovering a new and exciting taste sensation.",
            "Indulging in this dish was like stepping into a culinary fairy tale, where every flavor was a magical surprise.",
            "Tasting this recipe was like a journey through a flavor wonderland. Each bite was a delightful discovery!",
            "This dish is a culinary marvel, a testament to the artistry of flavors and the joy of gastronomic exploration."
        ])
    }
    comments.append(comment)

for _ in range(34):  # Continuing to reach a total of 100 comments
    comment = {
        "recipe_id": random.choice(recipe_ids),
        "user_id": random.choice(user_ids),
        "text": random.choice([
            "Exploring this dish was like embarking on a culinary adventure. The flavors are truly extraordinary.",
            "This recipe is a symphony for the senses. Every bite is a melodious blend of exquisite flavors.",
            "Delving into this culinary creation felt like discovering a secret garden of taste delights.",
            "Savoring this dish was like taking a sensory journey through a garden of culinary wonders.",
            "The flavors in this recipe are like a chorus of delicious notes, creating a harmonious masterpiece.",
            "Embarking on a taste adventure with this recipe was like discovering a hidden treasure of flavors.",
            "Tasting this dish was like attending a gourmet opera, where each flavor was a star performer.",
            "This recipe is a culinary marvel, a canvas of flavors that paints a delicious picture on the palate.",
            "Savoring this recipe was like sipping on the elixir of culinary excellence. Truly extraordinary!",
            "The flavors in this dish are like a symphony, each note harmonizing to create a delightful gastronomic experience.",
            "This recipe is a culinary adventure, with each bite uncovering a new and exciting taste sensation.",
            "Indulging in this dish was like stepping into a culinary fairy tale, where every flavor was a magical surprise.",
            "Tasting this recipe was like a journey through a flavor wonderland. Each bite was a delightful discovery!",
            "This dish is a culinary marvel, a testament to the artistry of flavors and the joy of gastronomic exploration.",
            "Savoring this recipe was like indulging in a feast for the senses. A symphony of flavors danced on my palate.",
            "Embarking on this culinary journey was like setting sail on a sea of exquisite tastes and aromas.",
            "The flavors in this dish are a captivating melody, leaving a lasting impression on the taste buds.",
            "Delving into this recipe was like entering a world where each flavor is a character in a culinary novel.",
            "Tasting this dish was like experiencing a culinary ballet, with each flavor gracefully pirouetting on my palate.",
            "This recipe is a gastronomic masterpiece, a culinary opus that leaves a lasting impression.",
            "Savoring this dish was like taking a culinary vacation, with each bite a passport to new and exciting flavors.",
            "Embarking on this flavor adventure was like exploring an uncharted territory of culinary delights.",
            "The flavors in this recipe are like a well-choreographed dance, each ingredient playing its part perfectly.",
            "Indulging in this dish was like attending a culinary showcase, with each flavor vying for the spotlight.",
            "Tasting this recipe was like enjoying a gourmet symphony, where each element played in perfect harmony.",
            "This dish is a culinary revelation, a testament to the artistry of flavors and the joy of gastronomic exploration.",
            "Savoring this recipe was like sipping on the elixir of culinary excellence. Truly extraordinary!",
            "The flavors in this dish are like a symphony, each note harmonizing to create a delightful gastronomic experience.",
            "This recipe is a culinary adventure, with each bite uncovering a new and exciting taste sensation.",
            "Indulging in this dish was like stepping into a culinary fairy tale, where every flavor was a magical surprise.",
            "Tasting this recipe was like a journey through a flavor wonderland. Each bite was a delightful discovery!",
            "This dish is a culinary marvel, a testament to the artistry of flavors and the joy of gastronomic exploration.",
            "Savoring this recipe was like indulging in a feast for the senses. A symphony of flavors danced on my palate.",
            "Embarking on this culinary journey was like setting sail on a sea of exquisite tastes and aromas.",
        ])
    }
    comments.append(comment)

