ingredients = [
    {
        'recipe_id': 1,
        'item': 'bacon',
        'measurement': 'ounce',
        'quantity': '8',
        'refridgerated': True,
    },
    {
        'recipe_id': 1,
        'item': 'onion',
        'measurement': 'large',
        'quantity': '1',
        'refridgerated': False,
    },
    {
        'recipe_id': 1,
        'item': 'garlic',
        'measurement': 'clove',
        'quantity': '1',
        'refridgerated': False,
    },
    {
        'recipe_id': 1,
        'item': 'potatoes',
        'measurement': 'pound',
        'quantity': '2',
        'refridgerated': False,
    },
    {
        'recipe_id': 1,
        'item': 'leek',
        'measurement': 'large',
        'quantity': '1',
        'refridgerated': True,
    },
    {
        'recipe_id': 1,
        'item': 'carrots',
        'measurement': 'medium',
        'quantity': '3',
        'refridgerated': True,
    },
    {
        'recipe_id': 1,
        'item': 'celery root',
        'measurement': 'cup',
        'quantity': '1.5',
        'refridgerated': True,
    },
    {
        'recipe_id': 1,
        'item': 'tomatoes',
        'measurement': 'medium',
        'quantity': '2',
        'refridgerated': False,
    },
    {
        'recipe_id': 1,
        'item': 'chicken broth',
        'measurement': 'cup',
        'quantity': '6',
        'refridgerated': False,
    },
    {
        'recipe_id': 1,
        'item': 'thyme',
        'measurement': 'teaspoon',
        'quantity': '.5',
        'refridgerated': False,
    },
    {
        'recipe_id': 1,
        'item': 'rosemary',
        'measurement': 'teaspoon',
        'quantity': '1/2',
        'refridgerated': False,
    },
    {
        'recipe_id': 1,
        'item': 'oregano',
        'measurement': 'teaspoon',
        'quantity': '1/2',
        'refridgerated': False,
    },
    {
        'recipe_id': 1,
        'item': 'salt',
        'measurement': 'teaspoon',
        'quantity': '3/4',
        'refridgerated': False,
    },
    {
        'recipe_id': 1,
        'item': 'pepper',
        'measurement': 'teaspoon',
        'quantity': '1/2',
        'refridgerated': False,
    },
    {
        'recipe_id': 1,
        'item': 'bay leaf',
        'measurement': 'whole item',
        'quantity': '1',
        'refridgerated': False,
    },
    {
        'recipe_id': 1,
        'item': 'parsley',
        'measurement': 'cup',
        'quantity': '1/4',
        'refridgerated': False,
    },
    {
        'recipe_id': 2,
        'item': 'garlic',
        'measurement': 'clove',
        'quantity': '4',
        'refridgerated': False,
    },
    {
        'recipe_id': 2,
        'item': 'lemon juice',
        'measurement': 'cup',
        'quantity': '.25',
        'refridgerated': True,
    },
     {
        'recipe_id': 2,
        'item': 'tahini',
        'measurement': 'cup',
        'quantity': '.5',
        'refridgerated': False,
    },
     {
        'recipe_id': 2,
        'item': 'ground cumin',
        'measurement': 'pinch',
        'quantity': '1',
        'refridgerated': False,
    },
     {
        'recipe_id': 2,
        'item': 'salt',
        'measurement': 'teaspoon',
        'quantity': '.5',
        'refridgerated': False,
    },
     {
        'recipe_id': 2,
        'item': 'ice water',
        'measurement': 'tablespoon',
        'quantity': '6',
        'refridgerated': False,
    },
    {
        'recipe_id': 3,
        'item': 'softened butter',
        'measurement': 'cup',
        'quantity': '1',
        'refridgerated': True,
    },
    {
        'recipe_id': 3,
        'item': 'brown sugar',
        'measurement': 'cup',
        'quantity': '1',
        'refridgerated': False,
    },
    {
        'recipe_id': 3,
        'item': 'sugar',
        'measurement': 'cup',
        'quantity': '.75',
        'refridgerated': False,
    },
    {
        'recipe_id': 3,
        'item': 'eggs',
        'measurement': 'large',
        'quantity': '2',
        'refridgerated': True,
    },
    {
        'recipe_id': 3,
        'item': 'vanilla extract',
        'measurement': 'teaspoon',
        'quantity': '1.5',
        'refridgerated': False,
    },
    {
        'recipe_id': 3,
        'item': 'all-purpose flour',
        'measurement': 'cup',
        'quantity': '2.75',
        'refridgerated': False,
    },
    {
        'recipe_id': 3,
        'item': 'baking soda',
        'measurement': 'teaspoon',
        'quantity': '1.25',
        'refridgerated': False,
    },
    {
        'recipe_id': 4,
        'item': 'all-purpose flour',
        'measurement': 'cup',
        'quantity': '1.5',
        'refridgerated': False,
    },
    {
        'recipe_id': 4,
        'item': 'baking powder',
        'measurement': 'teaspoon',
        'quantity': '3.5',
        'refridgerated': False,
    },
    {
        'recipe_id': 4,
        'item': 'white sugar',
        'measurement': 'tablespoon',
        'quantity': '1',
        'refridgerated': False,
    },
    {
        'recipe_id': 4,
        'item': 'salt',
        'measurement': 'teaspoon',
        'quantity': '.25',
        'refridgerated': False,
    },
    {
        'recipe_id': 4,
        'item': 'milk',
        'measurement': 'cup',
        'quantity': '1.25',
        'refridgerated': False,
    },
    {
        'recipe_id': 4,
        'item': 'melted butter',
        'measurement': 'tablespoon',
        'quantity': '3',
        'refridgerated': False,
    },
    {
        'recipe_id': 4,
        'item': 'egg',
        'measurement': 'whole item',
        'quantity': '1',
        'refridgerated': False,
    },
    {
        'recipe_id': 5,
        'item': 'olive oil',
        'measurement': 'tablespoon',
        'quantity': '2',
        'refridgerated': False,
    },
    {
        'recipe_id': 5,
        'item': 'garlic',
        'measurement': 'clove',
        'quantity': '1',
        'refridgerated': False,
    },
    {
        'recipe_id': 5,
        'item': 'bread crumbs',
        'measurement': 'cup',
        'quantity': '1',
        'refridgerated': False,
    },
    {
        'recipe_id': 5,
        'item': 'paremsean cheese',
        'measurement': 'cup',
        'quantity': '.75',
        'refridgerated': True,
    },
    {
        'recipe_id': 5,
        'item': 'dried basil',
        'measurement': 'teaspoon',
        'quantity': '.25',
        'refridgerated': False,
    },
    {
        'recipe_id': 5,
        'item': 'pepper',
        'measurement': 'teaspoon',
        'quantity': '.25',
        'refridgerated': False,
    },
    {
        'recipe_id': 5,
        'item': 'boneless chicken breast halves',
        'measurement': 'whole item',
        'quantity': '6',
        'refridgerated': False,
    },
]
